// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoConfigureClaude() {
  return window['go']['main']['App']['AutoConfigureClaude']();
}

export function AutoConfigureCursor() {
  return window['go']['main']['App']['AutoConfigureCursor']();
}

export function AutoConfigureVSCode(arg1, arg2) {
  return window['go']['main']['App']['AutoConfigureVSCode'](arg1, arg2);
}

export function ClearAuditLogs() {
  return window['go']['main']['App']['ClearAuditLogs']();
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DetectDBeaverFiles() {
  return window['go']['main']['App']['DetectDBeaverFiles']();
}

export function DetectTNSFiles() {
  return window['go']['main']['App']['DetectTNSFiles']();
}

export function ExecutePLSQL(arg1, arg2) {
  return window['go']['main']['App']['ExecutePLSQL'](arg1, arg2);
}

export function ExecuteQuery(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteQuery'](arg1, arg2, arg3);
}

export function GetActiveConnection() {
  return window['go']['main']['App']['GetActiveConnection']();
}

export function GetAuditLogs() {
  return window['go']['main']['App']['GetAuditLogs']();
}

export function GetConnections() {
  return window['go']['main']['App']['GetConnections']();
}

export function GetMCPServerStatus() {
  return window['go']['main']['App']['GetMCPServerStatus']();
}

export function GetSchemaObjects(arg1) {
  return window['go']['main']['App']['GetSchemaObjects'](arg1);
}

export function GetSecurityPolicy() {
  return window['go']['main']['App']['GetSecurityPolicy']();
}

export function GetTableSchema(arg1, arg2) {
  return window['go']['main']['App']['GetTableSchema'](arg1, arg2);
}

export function OpenSQLFile() {
  return window['go']['main']['App']['OpenSQLFile']();
}

export function ParseDBeaverFile(arg1) {
  return window['go']['main']['App']['ParseDBeaverFile'](arg1);
}

export function ParseTNSFile(arg1) {
  return window['go']['main']['App']['ParseTNSFile'](arg1);
}

export function RestartMCPServer(arg1) {
  return window['go']['main']['App']['RestartMCPServer'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveSQLFile(arg1, arg2) {
  return window['go']['main']['App']['SaveSQLFile'](arg1, arg2);
}

export function SaveSecurityPolicy(arg1) {
  return window['go']['main']['App']['SaveSecurityPolicy'](arg1);
}

export function SelectDBeaverFile() {
  return window['go']['main']['App']['SelectDBeaverFile']();
}

export function SelectTNSFile() {
  return window['go']['main']['App']['SelectTNSFile']();
}

export function SetActiveConnection(arg1) {
  return window['go']['main']['App']['SetActiveConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ValidateQueryTest(arg1) {
  return window['go']['main']['App']['ValidateQueryTest'](arg1);
}
