// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AutoConfigureClaude():Promise<string>;

export function AutoConfigureCursor():Promise<string>;

export function AutoConfigureVSCode(arg1:string):Promise<string>;

export function ClearAuditLogs():Promise<void>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DetectDBeaverFiles():Promise<Array<string>>;

export function DetectTNSFiles():Promise<Array<string>>;

export function ExecutePLSQL(arg1:string,arg2:string):Promise<models.PLSQLResult>;

export function ExecuteQuery(arg1:string,arg2:string,arg3:number):Promise<models.QueryResult>;

export function GetActiveConnection():Promise<models.ConnectionProfile>;

export function GetAuditLogs():Promise<Array<models.AuditLogEntry>>;

export function GetConnections():Promise<Array<models.ConnectionProfile>>;

export function GetMCPServerStatus():Promise<models.MCPServerStatus>;

export function GetSchemaObjects(arg1:string):Promise<models.SchemaInfo>;

export function GetSecurityPolicy():Promise<models.SecurityPolicy>;

export function GetTableSchema(arg1:string,arg2:string):Promise<Array<models.ColumnInfo>>;

export function ParseDBeaverFile(arg1:string):Promise<Array<models.ConnectionProfile>>;

export function ParseTNSFile(arg1:string):Promise<Array<models.TNSEntry>>;

export function RestartMCPServer(arg1:number):Promise<void>;

export function SaveConnection(arg1:models.ConnectionProfile):Promise<models.ConnectionProfile>;

export function SaveSecurityPolicy(arg1:models.SecurityPolicy):Promise<void>;

export function SelectDBeaverFile():Promise<string>;

export function SelectTNSFile():Promise<string>;

export function SetActiveConnection(arg1:string):Promise<void>;

export function TestConnection(arg1:models.ConnectionProfile):Promise<models.ConnectionTestResult>;

export function ValidateQueryTest(arg1:string):Promise<Record<string, any>>;
